//! CDN metrics collection and Prometheus-compatible export.
//!
//! # Overview
//!
//! [`CdnMetrics`] collects aggregate counters using [`AtomicU64`] for lock-free
//! increments from multiple threads.  [`EdgeMetrics`] provides per-edge-node
//! breakdowns.  [`MetricSnapshot`] captures a consistent point-in-time view of
//! all counters, and `to_prometheus` / [`MetricSnapshot::to_prometheus`]
//! format them in the Prometheus text exposition format.
//!
//! # Units
//!
//! - **bytes_served** — cumulative bytes transmitted to clients.
//! - **bandwidth_gb** — `bytes_served / 1_073_741_824` (GiB).
//! - **hit_ratio** / **miss_ratio** — fractions in `[0.0, 1.0]`.

use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};

// ─── CdnMetrics ───────────────────────────────────────────────────────────────

/// Global CDN counters — all fields are [`AtomicU64`] for lock-free updates.
#[derive(Debug, Default)]
pub struct CdnMetrics {
    /// Total HTTP requests received by the CDN.
    pub total_requests: AtomicU64,
    /// Requests served from cache.
    pub cache_hits: AtomicU64,
    /// Requests that missed the cache and fetched from origin.
    pub cache_misses: AtomicU64,
    /// Total bytes delivered to clients.
    pub bytes_served: AtomicU64,
    /// Total error responses (4xx + 5xx).
    pub errors: AtomicU64,
}

impl CdnMetrics {
    /// Create a new zero-initialised metrics instance.
    pub fn new() -> Self {
        Self::default()
    }

    /// Record a cache hit of `bytes` bytes.
    pub fn record_hit(&self, bytes: u64) {
        self.total_requests.fetch_add(1, Ordering::Relaxed);
        self.cache_hits.fetch_add(1, Ordering::Relaxed);
        self.bytes_served.fetch_add(bytes, Ordering::Relaxed);
    }

    /// Record a cache miss of `bytes` bytes (origin fetch).
    pub fn record_miss(&self, bytes: u64) {
        self.total_requests.fetch_add(1, Ordering::Relaxed);
        self.cache_misses.fetch_add(1, Ordering::Relaxed);
        self.bytes_served.fetch_add(bytes, Ordering::Relaxed);
    }

    /// Record an error response (does not count towards cache hits/misses).
    pub fn record_error(&self) {
        self.total_requests.fetch_add(1, Ordering::Relaxed);
        self.errors.fetch_add(1, Ordering::Relaxed);
    }

    /// Cache-hit ratio in `[0.0, 1.0]`.
    ///
    /// Returns `0.0` when `total_requests == 0`.
    pub fn hit_ratio(&self) -> f64 {
        let total = self.total_requests.load(Ordering::Relaxed);
        if total == 0 {
            return 0.0;
        }
        self.cache_hits.load(Ordering::Relaxed) as f64 / total as f64
    }

    /// Cache-miss ratio in `[0.0, 1.0]`.
    ///
    /// Returns `0.0` when `total_requests == 0`.
    pub fn miss_ratio(&self) -> f64 {
        let total = self.total_requests.load(Ordering::Relaxed);
        if total == 0 {
            return 0.0;
        }
        self.cache_misses.load(Ordering::Relaxed) as f64 / total as f64
    }

    /// Total bytes served converted to **gibibytes** (1 GiB = 2^30 bytes).
    pub fn total_bandwidth_gb(&self) -> f64 {
        self.bytes_served.load(Ordering::Relaxed) as f64 / 1_073_741_824.0
    }

    /// Capture a consistent [`MetricSnapshot`].
    pub fn snapshot(&self) -> MetricSnapshot {
        MetricSnapshot {
            total_requests: self.total_requests.load(Ordering::Relaxed),
            cache_hits: self.cache_hits.load(Ordering::Relaxed),
            cache_misses: self.cache_misses.load(Ordering::Relaxed),
            bytes_served: self.bytes_served.load(Ordering::Relaxed),
            errors: self.errors.load(Ordering::Relaxed),
        }
    }

    /// Render all counters in the **Prometheus text format** (v0.0.4).
    pub fn to_prometheus(&self) -> String {
        self.snapshot().to_prometheus()
    }
}

// ─── EdgeMetrics ─────────────────────────────────────────────────────────────

/// Per-edge-node metric counters.
#[derive(Debug, Default)]
pub struct EdgeMetrics {
    /// Identifier of the edge node.
    pub node_id: String,
    /// Requests handled by this node.
    pub total_requests: AtomicU64,
    /// Cache hits on this node.
    pub cache_hits: AtomicU64,
    /// Cache misses on this node.
    pub cache_misses: AtomicU64,
    /// Bytes served by this node.
    pub bytes_served: AtomicU64,
    /// Errors generated by this node.
    pub errors: AtomicU64,
}

impl EdgeMetrics {
    /// Create a new per-edge metrics instance.
    pub fn new(node_id: impl Into<String>) -> Self {
        Self {
            node_id: node_id.into(),
            ..Self::default()
        }
    }

    /// Record a cache hit.
    pub fn record_hit(&self, bytes: u64) {
        self.total_requests.fetch_add(1, Ordering::Relaxed);
        self.cache_hits.fetch_add(1, Ordering::Relaxed);
        self.bytes_served.fetch_add(bytes, Ordering::Relaxed);
    }

    /// Record a cache miss.
    pub fn record_miss(&self, bytes: u64) {
        self.total_requests.fetch_add(1, Ordering::Relaxed);
        self.cache_misses.fetch_add(1, Ordering::Relaxed);
        self.bytes_served.fetch_add(bytes, Ordering::Relaxed);
    }

    /// Record an error.
    pub fn record_error(&self) {
        self.total_requests.fetch_add(1, Ordering::Relaxed);
        self.errors.fetch_add(1, Ordering::Relaxed);
    }

    /// Cache-hit ratio for this node.
    pub fn hit_ratio(&self) -> f64 {
        let total = self.total_requests.load(Ordering::Relaxed);
        if total == 0 {
            return 0.0;
        }
        self.cache_hits.load(Ordering::Relaxed) as f64 / total as f64
    }

    /// Bandwidth in GiB served by this node.
    pub fn bandwidth_gb(&self) -> f64 {
        self.bytes_served.load(Ordering::Relaxed) as f64 / 1_073_741_824.0
    }

    /// Point-in-time snapshot.
    pub fn snapshot(&self) -> EdgeSnapshot {
        EdgeSnapshot {
            node_id: self.node_id.clone(),
            total_requests: self.total_requests.load(Ordering::Relaxed),
            cache_hits: self.cache_hits.load(Ordering::Relaxed),
            cache_misses: self.cache_misses.load(Ordering::Relaxed),
            bytes_served: self.bytes_served.load(Ordering::Relaxed),
            errors: self.errors.load(Ordering::Relaxed),
        }
    }
}

// ─── MetricSnapshot ───────────────────────────────────────────────────────────

/// Immutable point-in-time view of [`CdnMetrics`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MetricSnapshot {
    /// Total requests at snapshot time.
    pub total_requests: u64,
    /// Cache hits at snapshot time.
    pub cache_hits: u64,
    /// Cache misses at snapshot time.
    pub cache_misses: u64,
    /// Bytes served at snapshot time.
    pub bytes_served: u64,
    /// Errors at snapshot time.
    pub errors: u64,
}

impl MetricSnapshot {
    /// Cache-hit ratio.
    pub fn hit_ratio(&self) -> f64 {
        if self.total_requests == 0 {
            return 0.0;
        }
        self.cache_hits as f64 / self.total_requests as f64
    }

    /// Cache-miss ratio.
    pub fn miss_ratio(&self) -> f64 {
        if self.total_requests == 0 {
            return 0.0;
        }
        self.cache_misses as f64 / self.total_requests as f64
    }

    /// Total bandwidth in GiB.
    pub fn total_bandwidth_gb(&self) -> f64 {
        self.bytes_served as f64 / 1_073_741_824.0
    }

    /// Render this snapshot in the Prometheus text exposition format.
    ///
    /// Each metric is emitted with a `# HELP` and `# TYPE` header followed by
    /// its current value.
    pub fn to_prometheus(&self) -> String {
        let mut out = String::with_capacity(512);

        emit_counter(
            &mut out,
            "cdn_requests_total",
            "Total number of CDN requests.",
            self.total_requests,
        );
        emit_counter(
            &mut out,
            "cdn_cache_hits_total",
            "Total number of cache hits.",
            self.cache_hits,
        );
        emit_counter(
            &mut out,
            "cdn_cache_misses_total",
            "Total number of cache misses.",
            self.cache_misses,
        );
        emit_counter(
            &mut out,
            "cdn_bytes_served_total",
            "Total bytes served to clients.",
            self.bytes_served,
        );
        emit_counter(
            &mut out,
            "cdn_errors_total",
            "Total number of error responses.",
            self.errors,
        );

        // Derived gauge: hit ratio
        emit_gauge(
            &mut out,
            "cdn_cache_hit_ratio",
            "Cache hit ratio (0.0 – 1.0).",
            self.hit_ratio(),
        );

        out
    }
}

/// Immutable per-edge snapshot.
#[derive(Debug, Clone)]
pub struct EdgeSnapshot {
    /// Node identifier.
    pub node_id: String,
    /// Total requests.
    pub total_requests: u64,
    /// Cache hits.
    pub cache_hits: u64,
    /// Cache misses.
    pub cache_misses: u64,
    /// Bytes served.
    pub bytes_served: u64,
    /// Errors.
    pub errors: u64,
}

impl EdgeSnapshot {
    /// Render this snapshot in Prometheus format with node labels.
    pub fn to_prometheus(&self) -> String {
        let label = format!(r#"{{node="{}"}}"#, self.node_id);
        let mut out = String::with_capacity(512);

        emit_labeled_counter(
            &mut out,
            "cdn_edge_requests_total",
            "Total requests per edge node.",
            &label,
            self.total_requests,
        );
        emit_labeled_counter(
            &mut out,
            "cdn_edge_cache_hits_total",
            "Cache hits per edge node.",
            &label,
            self.cache_hits,
        );
        emit_labeled_counter(
            &mut out,
            "cdn_edge_bytes_served_total",
            "Bytes served per edge node.",
            &label,
            self.bytes_served,
        );
        emit_labeled_counter(
            &mut out,
            "cdn_edge_errors_total",
            "Errors per edge node.",
            &label,
            self.errors,
        );

        out
    }
}

// ─── Prometheus helpers ───────────────────────────────────────────────────────

fn emit_counter(out: &mut String, name: &str, help: &str, value: u64) {
    out.push_str(&format!(
        "# HELP {name} {help}\n# TYPE {name} counter\n{name} {value}\n"
    ));
}

fn emit_gauge(out: &mut String, name: &str, help: &str, value: f64) {
    out.push_str(&format!(
        "# HELP {name} {help}\n# TYPE {name} gauge\n{name} {value:.6}\n"
    ));
}

fn emit_labeled_counter(out: &mut String, name: &str, help: &str, label: &str, value: u64) {
    out.push_str(&format!(
        "# HELP {name} {help}\n# TYPE {name} counter\n{name}{label} {value}\n"
    ));
}

// ─── MetricsRegistry ─────────────────────────────────────────────────────────

/// A thread-safe registry that aggregates global and per-edge metrics.
pub struct MetricsRegistry {
    /// Global CDN-wide counters.
    pub global: Arc<CdnMetrics>,
    /// Per-edge-node counters keyed by node ID.
    edge: Mutex<HashMap<String, Arc<EdgeMetrics>>>,
}

impl MetricsRegistry {
    /// Create a new empty registry.
    pub fn new() -> Self {
        Self {
            global: Arc::new(CdnMetrics::new()),
            edge: Mutex::new(HashMap::new()),
        }
    }

    /// Obtain (or create) the [`EdgeMetrics`] for `node_id`.
    ///
    /// Returns a freshly-created (empty) [`EdgeMetrics`] if the lock is
    /// poisoned, so callers never need to handle an error.
    pub fn edge_metrics(&self, node_id: &str) -> Arc<EdgeMetrics> {
        match self.edge.lock() {
            Ok(mut guard) => guard
                .entry(node_id.to_string())
                .or_insert_with(|| Arc::new(EdgeMetrics::new(node_id)))
                .clone(),
            Err(_) => Arc::new(EdgeMetrics::new(node_id)),
        }
    }

    /// Record a hit on both the global and the per-edge counters.
    pub fn record_hit(&self, node_id: &str, bytes: u64) {
        self.global.record_hit(bytes);
        self.edge_metrics(node_id).record_hit(bytes);
    }

    /// Record a miss on both the global and the per-edge counters.
    pub fn record_miss(&self, node_id: &str, bytes: u64) {
        self.global.record_miss(bytes);
        self.edge_metrics(node_id).record_miss(bytes);
    }

    /// Record an error on both the global and the per-edge counters.
    pub fn record_error(&self, node_id: &str) {
        self.global.record_error();
        self.edge_metrics(node_id).record_error();
    }

    /// Render a complete Prometheus scrape payload (global + all edges).
    pub fn to_prometheus(&self) -> String {
        let mut out = self.global.to_prometheus();
        if let Ok(guard) = self.edge.lock() {
            for em in guard.values() {
                out.push_str(&em.snapshot().to_prometheus());
            }
        }
        out
    }

    /// List all registered edge node IDs.
    pub fn edge_node_ids(&self) -> Vec<String> {
        match self.edge.lock() {
            Ok(guard) => guard.keys().cloned().collect(),
            Err(_) => Vec::new(),
        }
    }
}

impl Default for MetricsRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // 1. Initial state is zero
    #[test]
    fn test_cdn_metrics_initial_state() {
        let m = CdnMetrics::new();
        assert_eq!(m.total_requests.load(Ordering::Relaxed), 0);
        assert_eq!(m.cache_hits.load(Ordering::Relaxed), 0);
        assert_eq!(m.cache_misses.load(Ordering::Relaxed), 0);
        assert_eq!(m.bytes_served.load(Ordering::Relaxed), 0);
        assert_eq!(m.errors.load(Ordering::Relaxed), 0);
    }

    // 2. record_hit increments correctly
    #[test]
    fn test_record_hit() {
        let m = CdnMetrics::new();
        m.record_hit(1024);
        assert_eq!(m.total_requests.load(Ordering::Relaxed), 1);
        assert_eq!(m.cache_hits.load(Ordering::Relaxed), 1);
        assert_eq!(m.bytes_served.load(Ordering::Relaxed), 1024);
    }

    // 3. record_miss increments correctly
    #[test]
    fn test_record_miss() {
        let m = CdnMetrics::new();
        m.record_miss(2048);
        assert_eq!(m.total_requests.load(Ordering::Relaxed), 1);
        assert_eq!(m.cache_misses.load(Ordering::Relaxed), 1);
        assert_eq!(m.bytes_served.load(Ordering::Relaxed), 2048);
    }

    // 4. record_error increments correctly
    #[test]
    fn test_record_error() {
        let m = CdnMetrics::new();
        m.record_error();
        assert_eq!(m.total_requests.load(Ordering::Relaxed), 1);
        assert_eq!(m.errors.load(Ordering::Relaxed), 1);
        assert_eq!(m.bytes_served.load(Ordering::Relaxed), 0);
    }

    // 5. hit_ratio with no requests → 0.0
    #[test]
    fn test_hit_ratio_no_requests() {
        let m = CdnMetrics::new();
        assert!((m.hit_ratio() - 0.0).abs() < 1e-10);
    }

    // 6. hit_ratio with mixed requests
    #[test]
    fn test_hit_ratio_mixed() {
        let m = CdnMetrics::new();
        m.record_hit(100);
        m.record_hit(100);
        m.record_miss(100);
        // 2 hits / 3 total
        assert!(
            (m.hit_ratio() - 2.0 / 3.0).abs() < 1e-10,
            "hit_ratio={}",
            m.hit_ratio()
        );
    }

    // 7. miss_ratio complement of hit_ratio
    #[test]
    fn test_miss_ratio() {
        let m = CdnMetrics::new();
        m.record_hit(0);
        m.record_miss(0);
        assert!((m.hit_ratio() + m.miss_ratio() - 1.0).abs() < 1e-10);
    }

    // 8. total_bandwidth_gb conversion
    #[test]
    fn test_total_bandwidth_gb() {
        let m = CdnMetrics::new();
        // 1 GiB = 1_073_741_824 bytes
        m.record_hit(1_073_741_824);
        let gb = m.total_bandwidth_gb();
        assert!((gb - 1.0).abs() < 1e-9, "gb={gb}");
    }

    // 9. snapshot captures current state
    #[test]
    fn test_snapshot_consistency() {
        let m = CdnMetrics::new();
        m.record_hit(512);
        m.record_miss(256);
        m.record_error();
        let snap = m.snapshot();
        assert_eq!(snap.total_requests, 3);
        assert_eq!(snap.cache_hits, 1);
        assert_eq!(snap.cache_misses, 1);
        assert_eq!(snap.bytes_served, 768);
        assert_eq!(snap.errors, 1);
    }

    // 10. snapshot hit_ratio
    #[test]
    fn test_snapshot_hit_ratio() {
        let snap = MetricSnapshot {
            total_requests: 4,
            cache_hits: 3,
            cache_misses: 1,
            bytes_served: 0,
            errors: 0,
        };
        assert!((snap.hit_ratio() - 0.75).abs() < 1e-10);
        assert!((snap.miss_ratio() - 0.25).abs() < 1e-10);
    }

    // 11. to_prometheus output contains expected labels
    #[test]
    fn test_to_prometheus_contains_labels() {
        let m = CdnMetrics::new();
        m.record_hit(1000);
        m.record_miss(500);
        let prom = m.to_prometheus();
        assert!(
            prom.contains("cdn_requests_total"),
            "missing cdn_requests_total"
        );
        assert!(prom.contains("cdn_cache_hits_total"), "missing hits");
        assert!(prom.contains("cdn_cache_misses_total"), "missing misses");
        assert!(prom.contains("cdn_bytes_served_total"), "missing bytes");
        assert!(prom.contains("cdn_errors_total"), "missing errors");
        assert!(prom.contains("cdn_cache_hit_ratio"), "missing hit_ratio");
        assert!(prom.contains("# HELP"), "missing HELP");
        assert!(prom.contains("# TYPE"), "missing TYPE");
    }

    // 12. EdgeMetrics basic operations
    #[test]
    fn test_edge_metrics_basic() {
        let em = EdgeMetrics::new("pop-iad-1");
        em.record_hit(4096);
        em.record_miss(2048);
        em.record_error();
        assert_eq!(em.total_requests.load(Ordering::Relaxed), 3);
        assert_eq!(em.cache_hits.load(Ordering::Relaxed), 1);
        assert!((em.hit_ratio() - 1.0 / 3.0).abs() < 1e-10);
    }

    // 13. EdgeMetrics snapshot
    #[test]
    fn test_edge_metrics_snapshot() {
        let em = EdgeMetrics::new("pop-lax");
        em.record_hit(1_073_741_824); // 1 GiB
        let snap = em.snapshot();
        assert_eq!(snap.node_id, "pop-lax");
        assert_eq!(snap.cache_hits, 1);
        assert!((em.bandwidth_gb() - 1.0).abs() < 1e-9);
    }

    // 14. EdgeSnapshot to_prometheus has node label
    #[test]
    fn test_edge_snapshot_to_prometheus() {
        let snap = EdgeSnapshot {
            node_id: "pop-test".to_string(),
            total_requests: 10,
            cache_hits: 7,
            cache_misses: 3,
            bytes_served: 1024,
            errors: 0,
        };
        let prom = snap.to_prometheus();
        assert!(prom.contains(r#"node="pop-test""#), "missing node label");
        assert!(prom.contains("cdn_edge_requests_total"), "missing requests");
    }

    // 15. MetricsRegistry aggregates global and edge
    #[test]
    fn test_metrics_registry_aggregate() {
        let reg = MetricsRegistry::new();
        reg.record_hit("edge-1", 1024);
        reg.record_hit("edge-2", 2048);
        reg.record_miss("edge-1", 512);
        reg.record_error("edge-2");

        // Global
        assert_eq!(reg.global.total_requests.load(Ordering::Relaxed), 4);
        assert_eq!(reg.global.cache_hits.load(Ordering::Relaxed), 2);

        // Per-edge
        let em1 = reg.edge_metrics("edge-1");
        assert_eq!(em1.total_requests.load(Ordering::Relaxed), 2);
        let em2 = reg.edge_metrics("edge-2");
        assert_eq!(em2.errors.load(Ordering::Relaxed), 1);
    }

    // 16. MetricsRegistry to_prometheus includes both global and edge sections
    #[test]
    fn test_registry_to_prometheus() {
        let reg = MetricsRegistry::new();
        reg.record_hit("pop-nyc", 100);
        let prom = reg.to_prometheus();
        assert!(prom.contains("cdn_requests_total"));
        assert!(prom.contains("cdn_edge_requests_total"));
        assert!(prom.contains(r#"node="pop-nyc""#));
    }

    // 17. edge_node_ids lists registered nodes
    #[test]
    fn test_edge_node_ids() {
        let reg = MetricsRegistry::new();
        reg.record_hit("node-a", 0);
        reg.record_miss("node-b", 0);
        let ids = reg.edge_node_ids();
        assert!(ids.contains(&"node-a".to_string()));
        assert!(ids.contains(&"node-b".to_string()));
    }

    // 18. Zero bandwidth_gb when nothing served
    #[test]
    fn test_zero_bandwidth() {
        let m = CdnMetrics::new();
        assert!((m.total_bandwidth_gb() - 0.0).abs() < 1e-15);
    }

    // 19. Errors do not count as hits or misses
    #[test]
    fn test_errors_not_counted_as_hits() {
        let m = CdnMetrics::new();
        m.record_error();
        m.record_error();
        assert_eq!(m.cache_hits.load(Ordering::Relaxed), 0);
        assert_eq!(m.cache_misses.load(Ordering::Relaxed), 0);
        assert_eq!(m.total_requests.load(Ordering::Relaxed), 2);
    }

    // 20. snapshot total_bandwidth_gb
    #[test]
    fn test_snapshot_total_bandwidth_gb() {
        let snap = MetricSnapshot {
            total_requests: 1,
            cache_hits: 1,
            cache_misses: 0,
            bytes_served: 1_073_741_824 * 2, // 2 GiB
            errors: 0,
        };
        assert!((snap.total_bandwidth_gb() - 2.0).abs() < 1e-9);
    }
}
